jobs:
  Publish_azure:
    name: azure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release azure octodns/azure
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_cloudflare:
    name: cloudflare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release cloudflare octodns/cloudflare
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_constellix:
    name: constellix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release constellix octodns/constellix
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_digitalocean:
    name: digitalocean
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release digitalocean octodns/digitalocean
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_dnsimple:
    name: dnsimple
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release dnsimple octodns/dnsimple
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_dnsmadeeasy:
    name: dnsmadeeasy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release dnsmadeeasy octodns/dnsmadeeasy
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_dyn:
    name: dyn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release dyn octodns/dyn
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_edgedns:
    name: edgedns
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release edgedns octodns/edgedns
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_etchosts:
    name: etchosts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release etchosts octodns/etchosts
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_gandi:
    name: gandi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release gandi octodns/gandi
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_gcore:
    name: gcore
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release gcore octodns/gcore
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_ns1:
    name: ns1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release ns1 octodns/ns1
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_powerdns:
    name: powerdns
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release powerdns octodns/powerdns
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
  Publish_route53:
    name: route53
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release route53 octodns/route53
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
name: Publish to Docker Hub on push to main
'on':
  push:
    branches:
    - main
    - github-actions
