jobs:
  Publish:
    name: Publish ${{matrix.flavor}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: octodns
      name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        "$DOCKER_REGISTRY_URL"'
    - name: Publish octodns
      run: script/release ${{matrix.flavor}} octodns/${{matrix.flavor}}
    - env:
        DOCKER_REGISTRY_URL: docker.io
      name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
    strategy:
      matrix:
        flavor:
        - azure
        - bind
        - cloudflare
        - constellix
        - digitalocean
        - dnsimple
        - dnsmadeeasy
        - dyn
        - easydns
        - edgedns
        - etchosts
        - gandi
        - gcore
        - googlecloud
        - hetzner
        - mythicbeasts
        - ns1
        - octodns
        - ovh
        - powerdns
        - rackspace
        - route53
        - selectel
        - transip
        - ultra
name: Publish to Docker Hub on push to main
'on':
  push:
    branches:
    - main
    - github-actions
