---
'on':
  push:
    branches:
    - main
    - github-actions
name: Publish to Docker Hub on push to main
jobs:
  Publish_all:
    name: Publish all flavor
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"'
      env:
        DOCKER_USERNAME: octodns
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        DOCKER_REGISTRY_URL: docker.io
    - name: Publish octodns
      run: script/release all octodns/octodns
    - name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
      env:
        DOCKER_REGISTRY_URL: docker.io
  Publish_cloudflare:
    name: Publish cloudflare flavor
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: bash -c 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"'
      env:
        DOCKER_USERNAME: octodns
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        DOCKER_REGISTRY_URL: docker.io
    - name: Publish octodns
      run: script/release cloudflare octodns/cloudflare
    - name: Docker Logout
      run: docker logout "$DOCKER_REGISTRY_URL"
      env:
        DOCKER_REGISTRY_URL: docker.io
