---
'on': push
name: Test
jobs:
  Test_all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild all octodns
  Test_azure:
    name: azure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild azure azure
  Test_cloudflare:
    name: cloudflare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild cloudflare cloudflare
  Test_constellix:
    name: constellix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild constellix constellix
  Test_digitalocean:
    name: digitalocean
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild digitalocean digitalocean
  Test_dnsimple:
    name: dnsimple
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild dnsimple dnsimple
  Test_dnsmadeeasy:
    name: dnsmadeeasy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild dnsmadeeasy dnsmadeeasy
  Test_dyn:
    name: dyn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild dyn dyn
  Test_ns1:
    name: ns1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild ns1 ns1
  Test_powerdns:
    name: powerdns
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild powerdns powerdns
  Test_route53:
    name: route53
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/cibuild route53 route53
