jobs:
  Test:
    name: Test ${{matrix.flavor}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: script/cibuild ${{matrix.flavor}} ${{matrix.flavor}}
    strategy:
      matrix:
        flavor:
        - azure
        - bind
        - cloudflare
        - constellix
        - digitalocean
        - dnsimple
        - dnsmadeeasy
        - dyn
        - easydns
        - edgedns
        - etchosts
        - gandi
        - gcore
        - googlecloud
        - hetzner
        - mythicbeasts
        - ns1
        - octodns
        - ovh
        - powerdns
        - rackspace
        - route53
        - selectel
        - transip
        - ultra
name: Test
'on': push
